In [1]:
import pandas as pd
import numpy as np

data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'Department': ['HR', 'IT', 'IT', 'Sales', 'HR', 'Sales', 'IT', 'Finance', 'Sales', 'Finance'],
    'Salary': [70000, 85000, 82000, 55000, np.nan, 58000, 91000, 95000, 62000, 88000],
    'Years_Exp': [5, np.nan, 7, 3, 2, 4, 10, 12, 5, 9],
    'Remote': [True, False, False, True, True, False, False, False, True, False]
}

df = pd.DataFrame(data)
display(df)

   Employee_ID     Name Department   Salary  Years_Exp  Remote
0          101    Alice         HR  70000.0        5.0    True
1          102      Bob         IT  85000.0        NaN   False
2          103  Charlie         IT  82000.0        7.0   False
3          104    David      Sales  55000.0        3.0    True
4          105      Eva         HR      NaN        2.0    True
5          106    Frank      Sales  58000.0        4.0   False
6          107    Grace         IT  91000.0       10.0   False
7          108    Henry    Finance  95000.0       12.0   False
8          109      Ivy      Sales  62000.0        5.0    True
9          110     Jack    Finance  88000.0        9.0   False

In [2]:
df.head()

   Employee_ID     Name Department   Salary  Years_Exp  Remote
0          101    Alice         HR  70000.0        5.0    True
1          102      Bob         IT  85000.0        NaN   False
2          103  Charlie         IT  82000.0        7.0   False
3          104    David      Sales  55000.0        3.0    True
4          105      Eva         HR      NaN        2.0    True

In [3]:
df.tail()

   Employee_ID   Name Department   Salary  Years_Exp  Remote
5          106  Frank      Sales  58000.0        4.0   False
6          107  Grace         IT  91000.0       10.0   False
7          108  Henry    Finance  95000.0       12.0   False
8          109    Ivy      Sales  62000.0        5.0    True
9          110   Jack    Finance  88000.0        9.0   False

In [4]:
df.describe()

       Employee_ID        Salary  Years_Exp
count     10.00000      9.000000   9.000000
mean     105.50000  76222.222222   6.333333
std        3.02765  15180.396716   3.391165
min      101.00000  55000.000000   2.000000
25%      103.25000  62000.000000   4.000000
50%      105.50000  82000.000000   5.000000
75%      107.75000  88000.000000   9.000000
max      110.00000  95000.000000  12.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  10 non-null     int64
 1   Name         10 non-null     object
 2   Department   10 non-null     object
 3   Salary       9 non-null      float64
 4   Years_Exp    9 non-null      float64
 5   Remote       10 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(2)
memory usage: 538.0+ bytes

In [6]:
df.isnull()

   Employee_ID   Name  Department  Salary  Years_Exp  Remote
0        False  False       False   False      False   False
1        False  False       False   False       True   False
2        False  False       False   False      False   False
3        False  False       False   False      False   False
4        False  False       False    True      False   False
5        False  False       False   False      False   False
6        False  False       False   False      False   False
7        False  False       False   False      False   False
8        False  False       False   False      False   False
9        False  False       False   False      False   False

In [7]:
df.isnull().sum()

Employee_ID    0
Name           0
Department     0
Salary         1
Years_Exp      1
Remote         0
dtype: int64

In [8]:
df['Years_Exp'].isnull().sum()

np.int64(1)