In [119]:
import pandas as pd
import numpy as np

data = {
        'CustomerID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
        'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'George', 'Hannah', 'Ivy', 'Jack'],
        'Age': [25, 30, None, 45, 21, 34, 40, 28, 31, 26],
        'Gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Female', 'MALE'],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
        'PurchaseAmount': [150.50, 200.00, np.nan, 50.75, 120.00, -30.00, 8000.00, 45.20, 100.00, 90.00],
        'JoinDate': ['2023-01-15', '2023/02/20', 'Jan 1, 2024', '2023-04-10', '2023-05-05', '2023-01-15', '2023-07-30', '2023-08-25', '2023-09-19', '2023-10-14'],
        'Email': ['alice@example.com', 'bob@example.com', 'charlie@test.com', 'david@example.com', 'eve@test.com', 'frank@example.com', 'george@example.com', 'hannah@test.com', 'ivy@example.com', 'jack@example.com'],
        'Status': ['Active', 'Active', 'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active', 'Active']
    }
    
df = pd.DataFrame(data)

display(df)

,CustomerID,Name,Age,Gender,City,PurchaseAmount,JoinDate,Email,Status
0,101,Alice,25.0,Female,New York,150.50,2023-01-15,alice@example.com,Active
1,102,Bob,30.0,Male,Los Angeles,200.00,2023/02/20,bob@example.com,Active
2,103,Charlie,NaN,Male,Chicago,NaN,"Jan 1, 2024",charlie@test.com,Inactive
3,104,David,45.0,Male,Houston,50.75,2023-04-10,david@example.com,Active
4,105,Eve,21.0,Female,Phoenix,120.00,2023-05-05,eve@test.com,Active
5,106,Frank,34.0,Male,New York,-30.00,2023-01-15,frank@example.com,Active
6,107,George,40.0,Male,Los Angeles,8000.00,2023-07-30,george@example.com,Active
7,108,Hannah,28.0,Female,Chicago,45.20,2023-08-25,hannah@test.com,Active
8,109,Ivy,31.0,Female,Houston,100.00,2023-09-19,ivy@example.com,Active
9,110,Jack,26.0,MALE,Phoenix,90.00,2023-10-14,jack@example.com,Active

In [120]:
df['Gender'] = df['Gender'].str.lower()
df['Gender']

0    female
1      male
2      male
3      male
4    female
5      male
6      male
7    female
8    female
9      male
Name: Gender, dtype: object

In [121]:
df = df.replace('female', 'Female')
df = df.replace('male', 'Male')
df['Gender']

0    Female
1      Male
2      Male
3      Male
4    Female
5      Male
6      Male
7    Female
8    Female
9      Male
Name: Gender, dtype: object

In [122]:
df['Age'].isna().sum()

np.int64(1)

In [123]:
df['Age']  = df['Age'].fillna(df['Age'].mode()).astype(int)
df['Age']

0    25
1    30
2    26
3    45
4    21
5    34
6    40
7    28
8    31
9    26
Name: Age, dtype: int64

In [124]:
df['PurchaseAmount'] = df['PurchaseAmount'].fillna(df['PurchaseAmount'].mean())
df

,CustomerID,Name,Age,Gender,City,PurchaseAmount,JoinDate,Email,Status
0,101,Alice,25,Female,New York,150.500000,2023-01-15,alice@example.com,Active
1,102,Bob,30,Male,Los Angeles,200.000000,2023/02/20,bob@example.com,Active
2,103,Charlie,26,Male,Chicago,969.605556,"Jan 1, 2024",charlie@test.com,Inactive
3,104,David,45,Male,Houston,50.750000,2023-04-10,david@example.com,Active
4,105,Eve,21,Female,Phoenix,120.000000,2023-05-05,eve@test.com,Active
5,106,Frank,34,Male,New York,-30.000000,2023-01-15,frank@example.com,Active
6,107,George,40,Male,Los Angeles,8000.000000,2023-07-30,george@example.com,Active
7,108,Hannah,28,Female,Chicago,45.200000,2023-08-25,hannah@test.com,Active
8,109,Ivy,31,Female,Houston,100.000000,2023-09-19,ivy@example.com,Active
9,110,Jack,26,Male,Phoenix,90.000000,2023-10-14,jack@example.com,Active

In [125]:
df[df['PurchaseAmount']<0]

,CustomerID,Name,Age,Gender,City,PurchaseAmount,JoinDate,Email,Status
5,106,Frank,34,Male,New York,-30.0,2023-01-15,frank@example.com,Active

In [126]:
df.loc[df['PurchaseAmount']<0, 'PurchaseAmount'] = df['PurchaseAmount'].mean()
df

,CustomerID,Name,Age,Gender,City,PurchaseAmount,JoinDate,Email,Status
0,101,Alice,25,Female,New York,150.500000,2023-01-15,alice@example.com,Active
1,102,Bob,30,Male,Los Angeles,200.000000,2023/02/20,bob@example.com,Active
2,103,Charlie,26,Male,Chicago,969.605556,"Jan 1, 2024",charlie@test.com,Inactive
3,104,David,45,Male,Houston,50.750000,2023-04-10,david@example.com,Active
4,105,Eve,21,Female,Phoenix,120.000000,2023-05-05,eve@test.com,Active
5,106,Frank,34,Male,New York,969.605556,2023-01-15,frank@example.com,Active
6,107,George,40,Male,Los Angeles,8000.000000,2023-07-30,george@example.com,Active
7,108,Hannah,28,Female,Chicago,45.200000,2023-08-25,hannah@test.com,Active
8,109,Ivy,31,Female,Houston,100.000000,2023-09-19,ivy@example.com,Active
9,110,Jack,26,Male,Phoenix,90.000000,2023-10-14,jack@example.com,Active

In [127]:
df[df['PurchaseAmount']<0]

Empty DataFrame
Columns: [CustomerID, Name, Age, Gender, City, PurchaseAmount, JoinDate, Email, Status]
Index: []

In [128]:
df['City']

0       New York
1    Los Angeles
2        Chicago
3        Houston
4        Phoenix
5       New York
6    Los Angeles
7        Chicago
8        Houston
9        Phoenix
Name: City, dtype: object

In [129]:
df['JoinDate'] = pd.to_datetime(df['JoinDate'], errors='coerce', format='mixed')
df['JoinDate']

0   2023-01-15
1   2023-02-20
2   2024-01-01
3   2023-04-10
4   2023-05-05
5   2023-01-15
6   2023-07-30
7   2023-08-25
8   2023-09-19
9   2023-10-14
Name: JoinDate, dtype: datetime64[ns]

In [130]:
df

,CustomerID,Name,Age,Gender,City,PurchaseAmount,JoinDate,Email,Status
0,101,Alice,25,Female,New York,150.500000,2023-01-15,alice@example.com,Active
1,102,Bob,30,Male,Los Angeles,200.000000,2023-02-20,bob@example.com,Active
2,103,Charlie,26,Male,Chicago,969.605556,2024-01-01,charlie@test.com,Inactive
3,104,David,45,Male,Houston,50.750000,2023-04-10,david@example.com,Active
4,105,Eve,21,Female,Phoenix,120.000000,2023-05-05,eve@test.com,Active
5,106,Frank,34,Male,New York,969.605556,2023-01-15,frank@example.com,Active
6,107,George,40,Male,Los Angeles,8000.000000,2023-07-30,george@example.com,Active
7,108,Hannah,28,Female,Chicago,45.200000,2023-08-25,hannah@test.com,Active
8,109,Ivy,31,Female,Houston,100.000000,2023-09-19,ivy@example.com,Active
9,110,Jack,26,Male,Phoenix,90.000000,2023-10-14,jack@example.com,Active