In [83]:
import pandas as pd
import numpy as np

data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'Department': ['HR', 'IT', 'IT', 'Sales', 'HR', 'Sales', 'IT', 'Finance', 'Sales', 'Finance'],
    'Salary': [70000, 85000, 82000, 55000, np.nan, 58000, 91000, 95000, 62000, 88000],
    'Years_Exp': [5, 1, 7, 3, 2, 4, 10, 12, 5, 9],
    'Remote': [True, False, False, True, True, False, False, False, True, False]
}

df = pd.DataFrame(data)
display(df)

   Employee_ID     Name Department   Salary  Years_Exp  Remote
0          101    Alice         HR  70000.0          5    True
1          102      Bob         IT  85000.0          1   False
2          103  Charlie         IT  82000.0          7   False
3          104    David      Sales  55000.0          3    True
4          105      Eva         HR      NaN          2    True
5          106    Frank      Sales  58000.0          4   False
6          107    Grace         IT  91000.0         10   False
7          108    Henry    Finance  95000.0         12   False
8          109      Ivy      Sales  62000.0          5    True
9          110     Jack    Finance  88000.0          9   False

In [84]:
df.groupby('Department')['Salary'].sum()

Department
Finance    183000.0
HR          70000.0
IT         258000.0
Sales      175000.0
Name: Salary, dtype: float64

In [85]:
department = df.groupby('Department')

In [86]:
department.__dict__

{'_selection': None,
 'level': None,
 'as_index': True,
 'keys': 'Department',
 'sort': True,
 'group_keys': True,
 'dropna': True,
 'observed': False,
 'obj':    Employee_ID     Name Department   Salary  Years_Exp  Remote
 0          101    Alice         HR  70000.0          5    True
 1          102      Bob         IT  85000.0          1   False
 2          103  Charlie         IT  82000.0          7   False
 3          104    David      Sales  55000.0          3    True
 4          105      Eva         HR      NaN          2    True
 5          106    Frank      Sales  58000.0          4   False
 6          107    Grace         IT  91000.0         10   False
 7          108    Henry    Finance  95000.0         12   False
 8          109      Ivy      Sales  62000.0          5    True
 9          110     Jack    Finance  88000.0          9   False,
 'axis': 0,
 '_grouper': <pandas.core.groupby.ops.BaseGrouper at 0x716ee1c02860>,
 'exclusions': frozenset({'Department'})}

In [87]:
department.first() # print the first entries in all the groups formed.

            Employee_ID   Name   Salary  Years_Exp  Remote
Department
Finance             108  Henry  95000.0         12   False
HR                  101  Alice  70000.0          5    True
IT                  102    Bob  85000.0          1   False
Sales               104  David  55000.0          3    True

In [88]:
for row in department:
    print(row, end='\n\n')

('Finance',    Employee_ID   Name Department   Salary  Years_Exp  Remote
7          108  Henry    Finance  95000.0         12   False
9          110   Jack    Finance  88000.0          9   False)

('HR',    Employee_ID   Name Department   Salary  Years_Exp  Remote
0          101  Alice         HR  70000.0          5    True
4          105    Eva         HR      NaN          2    True)

('IT',    Employee_ID     Name Department   Salary  Years_Exp  Remote
1          102      Bob         IT  85000.0          1   False
2          103  Charlie         IT  82000.0          7   False
6          107    Grace         IT  91000.0         10   False)

('Sales',    Employee_ID   Name Department   Salary  Years_Exp  Remote
3          104  David      Sales  55000.0          3    True
5          106  Frank      Sales  58000.0          4   False
8          109    Ivy      Sales  62000.0          5    True)

In [89]:
grouping = df.groupby(["Department", "Remote"])
grouping.first()

                   Employee_ID   Name   Salary  Years_Exp
Department Remote
Finance    False           108  Henry  95000.0         12
HR         True            101  Alice  70000.0          5
IT         False           102    Bob  85000.0          1
Sales      False           106  Frank  58000.0          4
           True            104  David  55000.0          3

In [90]:
for row in grouping:
    print(row, end='\n\n')

(('Finance', np.False_),    Employee_ID   Name Department   Salary  Years_Exp  Remote
7          108  Henry    Finance  95000.0         12   False
9          110   Jack    Finance  88000.0          9   False)

(('HR', np.True_),    Employee_ID   Name Department   Salary  Years_Exp  Remote
0          101  Alice         HR  70000.0          5    True
4          105    Eva         HR      NaN          2    True)

(('IT', np.False_),    Employee_ID     Name Department   Salary  Years_Exp  Remote
1          102      Bob         IT  85000.0          1   False
2          103  Charlie         IT  82000.0          7   False
6          107    Grace         IT  91000.0         10   False)

(('Sales', np.False_),    Employee_ID   Name Department   Salary  Years_Exp  Remote
5          106  Frank      Sales  58000.0          4   False)

(('Sales', np.True_),    Employee_ID   Name Department   Salary  Years_Exp  Remote
3          104  David      Sales  55000.0          3    True
8          109    Ivy      Sales  62000.0          5    True)

In [91]:
filtered_df = df.groupby('Department').filter(lambda x: x['Salary'].mean() >= 80000)
print(filtered_df)

   Employee_ID     Name Department   Salary  Years_Exp  Remote
1          102      Bob         IT  85000.0          1   False
2          103  Charlie         IT  82000.0          7   False
6          107    Grace         IT  91000.0         10   False
7          108    Henry    Finance  95000.0         12   False
9          110     Jack    Finance  88000.0          9   False

In [92]:
group_means = df.groupby('Department')['Salary'].mean()
result = group_means[group_means >= 50000]
print(result)

Department
Finance    91500.000000
HR         70000.000000
IT         86000.000000
Sales      58333.333333
Name: Salary, dtype: float64

In [93]:
df['Salary'] = df['Salary'].apply(lambda x : x+5000)

In [94]:
df

   Employee_ID     Name Department    Salary  Years_Exp  Remote
0          101    Alice         HR   75000.0          5    True
1          102      Bob         IT   90000.0          1   False
2          103  Charlie         IT   87000.0          7   False
3          104    David      Sales   60000.0          3    True
4          105      Eva         HR       NaN          2    True
5          106    Frank      Sales   63000.0          4   False
6          107    Grace         IT   96000.0         10   False
7          108    Henry    Finance  100000.0         12   False
8          109      Ivy      Sales   67000.0          5    True
9          110     Jack    Finance   93000.0          9   False

In [ ]:
df['Name'] = df['Name'].str.lower()
df['Name']

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Years_Exp', 'Remote'], dtype='object')

0      alice
1        bob
2    charlie
3      david
4        eva
5      frank
6      grace
7      henry
8        ivy
9       jack
Name: Name, dtype: object

In [98]:
def update_name(name): return name.upper()
df['Name'] = df['Name'].apply(update_name)
df['Name']

0      ALICE
1        BOB
2    CHARLIE
3      DAVID
4        EVA
5      FRANK
6      GRACE
7      HENRY
8        IVY
9       JACK
Name: Name, dtype: object