In [34]:
import pandas as pd
import numpy as np

data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'],
    'Department': ['HR', 'IT', 'IT', 'Sales', 'HR', 'Sales', 'IT', 'Finance', 'Sales', 'Finance'],
    'Salary': [70000, 85000, 82000, 55000, np.nan, 58000, 91000, 95000, 62000, 88000],
    'Years_Exp': [5, 1, 7, 3, 2, 4, 10, 12, 5, 9],
    'Remote': [True, False, False, True, True, False, False, False, True, False]
}

df = pd.DataFrame(data)
display(df)

   Employee_ID     Name Department   Salary  Years_Exp  Remote
0          101    Alice         HR  70000.0          5    True
1          102      Bob         IT  85000.0          1   False
2          103  Charlie         IT  82000.0          7   False
3          104    David      Sales  55000.0          3    True
4          105      Eva         HR      NaN          2    True
5          106    Frank      Sales  58000.0          4   False
6          107    Grace         IT  91000.0         10   False
7          108    Henry    Finance  95000.0         12   False
8          109      Ivy      Sales  62000.0          5    True
9          110     Jack    Finance  88000.0          9   False

In [10]:
#df[0, 'Name'] # Wrong syntax
df.loc[0]['Name']

'Alice'

In [11]:
df[df['Department'] =='IT'] # persons with department IT

   Employee_ID     Name Department   Salary  Years_Exp  Remote
1          102      Bob         IT  85000.0          1   False
2          103  Charlie         IT  82000.0          7   False
6          107    Grace         IT  91000.0         10   False

In [14]:
df[(df['Department'] == 'IT' ) & (df['Years_Exp'] > 5)]

   Employee_ID     Name Department   Salary  Years_Exp  Remote
2          103  Charlie         IT  82000.0          7   False
6          107    Grace         IT  91000.0         10   False

In [15]:
df.loc[(df['Department'] == 'IT' ) & (df['Years_Exp'] > 5)]

   Employee_ID     Name Department   Salary  Years_Exp  Remote
2          103  Charlie         IT  82000.0          7   False
6          107    Grace         IT  91000.0         10   False

In [16]:
conditions = (df['Department'] == 'IT' ) & (df['Years_Exp'] > 5)
df[conditions]

   Employee_ID     Name Department   Salary  Years_Exp  Remote
2          103  Charlie         IT  82000.0          7   False
6          107    Grace         IT  91000.0         10   False

In [20]:
conditions = (df['Department'] == 'IT' ) & (df['Years_Exp'] > 5)
cols = ['Name', 'Department']
# df[conditions, cols] #incorrect df[...] only accepts bool , columns or row
df.loc[conditions, cols]

      Name Department
2  Charlie         IT
6    Grace         IT

In [21]:
df.loc[1]

Employee_ID        102
Name               Bob
Department          IT
Salary         85000.0
Years_Exp            1
Remote           False
Name: 1, dtype: object

In [35]:
df = df.set_index('Employee_ID')
df

                Name Department   Salary  Years_Exp  Remote
Employee_ID
101            Alice         HR  70000.0          5    True
102              Bob         IT  85000.0          1   False
103          Charlie         IT  82000.0          7   False
104            David      Sales  55000.0          3    True
105              Eva         HR      NaN          2    True
106            Frank      Sales  58000.0          4   False
107            Grace         IT  91000.0         10   False
108            Henry    Finance  95000.0         12   False
109              Ivy      Sales  62000.0          5    True
110             Jack    Finance  88000.0          9   False

In [ ]:
df.loc[109]
# df.iloc[109] #will not work

Name              Ivy
Department      Sales
Salary        62000.0
Years_Exp           5
Remote           True
Name: 109, dtype: object

In [39]:
df = df.reset_index()
df

   index  Employee_ID     Name Department   Salary  Years_Exp  Remote
0      0          101    Alice         HR  70000.0          5    True
1      1          102      Bob         IT  85000.0          1   False
2      2          103  Charlie         IT  82000.0          7   False
3      3          104    David      Sales  55000.0          3    True
4      4          105      Eva         HR      NaN          2    True
5      5          106    Frank      Sales  58000.0          4   False
6      6          107    Grace         IT  91000.0         10   False
7      7          108    Henry    Finance  95000.0         12   False
8      8          109      Ivy      Sales  62000.0          5    True
9      9          110     Jack    Finance  88000.0          9   False

In [40]:
df.loc[1:5]

   index  Employee_ID     Name Department   Salary  Years_Exp  Remote
1      1          102      Bob         IT  85000.0          1   False
2      2          103  Charlie         IT  82000.0          7   False
3      3          104    David      Sales  55000.0          3    True
4      4          105      Eva         HR      NaN          2    True
5      5          106    Frank      Sales  58000.0          4   False

In [ ]:
df.loc[1:5, 'Employee_ID' : 'Salary'] #all columns between them will be in output

   Employee_ID     Name Department   Salary
1          102      Bob         IT  85000.0
2          103  Charlie         IT  82000.0
3          104    David      Sales  55000.0
4          105      Eva         HR      NaN
5          106    Frank      Sales  58000.0

In [ ]:
df.loc[1:5, ['Employee_ID', 'Salary']] # only given columns

   Employee_ID   Salary
1          102  85000.0
2          103  82000.0
3          104  55000.0
4          105      NaN
5          106  58000.0

In [45]:
df

   index  Employee_ID     Name Department   Salary  Years_Exp  Remote
0      0          101    Alice         HR  70000.0          5    True
1      1          102      Bob         IT  85000.0          1   False
2      2          103  Charlie         IT  82000.0          7   False
3      3          104    David      Sales  55000.0          3    True
4      4          105      Eva         HR      NaN          2    True
5      5          106    Frank      Sales  58000.0          4   False
6      6          107    Grace         IT  91000.0         10   False
7      7          108    Henry    Finance  95000.0         12   False
8      8          109      Ivy      Sales  62000.0          5    True
9      9          110     Jack    Finance  88000.0          9   False

In [46]:
df.iloc[1]

index                1
Employee_ID        102
Name               Bob
Department          IT
Salary         85000.0
Years_Exp            1
Remote           False
Name: 1, dtype: object

In [48]:
df.iloc[[1,5,7,9]]

   index  Employee_ID   Name Department   Salary  Years_Exp  Remote
1      1          102    Bob         IT  85000.0          1   False
5      5          106  Frank      Sales  58000.0          4   False
7      7          108  Henry    Finance  95000.0         12   False
9      9          110   Jack    Finance  88000.0          9   False

In [ ]:
df.iloc[0:3, 0:3] # here we can not use Column name

   index  Employee_ID     Name
0      0          101    Alice
1      1          102      Bob
2      2          103  Charlie